name: Build
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.16.3]

    steps:
      - uses: actions/checkout@v1

      - name: Node 10.16.3
        uses: actions/setup-node@v1
        with:
          node-version: 10.16.3

      - name: install and build
        run: |
          npm install -g @angular/cli
          npm install
          ng build --prod
